spring:
  profiles: h2
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: false
        default_batch_fetch_size: 1000
    show-sql: true
    generate-ddl: true
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
  h2:
    console:
      enabled: true